### ISSUE TITLE
no config.xml file

### ISSUE THREAD

**Issue by criesbeck** [balakirevs/clicker#1]
Every step worked until ionic add platform android, which fails because there is no config.xml in the repo.  Is there some missing step? Other Ionic repos include their config.xml file.

**Comment by balakirevs** [comment]
added config.xml which was mistakenly gitignored.
Could you try ?

**Comment by criesbeck** [comment]
Seemed to work. I could launch the emulator with it. Still trying to get Appium to work but I'll report on that when I know more. 

One bug for sure: [A change in SpecReporter](https://github.com/bcaudan/jasmine-spec-reporter/tree/master/examples/node)  affects the protractor config files. Instead of 

var SpecReporter = require('jasmine-spec-reporter');

you need to say something equivalent to

const SpecReporter = require('jasmine-spec-reporter').SpecReporter;

Otherwise you get a no constructor for SpecReporter error. 

I then got [the Appium  ChromeDriver version error](https://github.com/appium/appium/issues/7138). Fixed that by downloading the most recent CD and passing it to appium with --chromedriver-executable

Now I'm getting a failure on the first Clicker test ("should have a title"). It seems to be because the emulator window is waiting for a response to "open with" and two options: Chrome and Webview Browser Tester. Haven't had time to web search about that yet.

Thanks for the starter template!
